language: python
python:
        - "2.7"
before_install:
        - sudo add-apt-repository ppa:fenics-packages/fenics -y
        - sudo apt-get update -q
        - sudo apt-get install fenics
script:
        - py.test
