language: python
python:
        - "2.7"
before_script:
        - sudo add-apt-repository ppa:fenics-packages/fenics -y
        - sudo apt-get update -q
        - sudo apt-get install cmake libopenmpi-dev python-dev libblas-dev liblapack-dev wget libboost-program-options1.48-dev libboost-filesystem1.48-dev libboost-serialization1.48-dev libboost-thread1.48-dev libboost-iostreams1.48-dev libboost-math1.48-dev libboost-timer1.48-dev libboost-chrono1.48-dev
        - sudo apt-get install fenics
script:
        - py.test
