language: python
python:
        - "2.6"
        - "2.7"
before_script:
        - sudo add-apt-repository ppa:fenics-packages/fenics -y
        - sudo apt-get update -q
        - sudo apt-get install fenics
        - sudo apt-get dist-upgrade
script:
        - py.test